import markdown
import nh3
from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect

# Strict allowlist of tags generated by standard Markdown
ALLOWED_TAGS = {
    'p', 'br', 'strong', 'em', 'u', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'ul', 'ol', 'li', 'code', 'pre', 'blockquote', 'a', 'hr', 'table',
    'thead', 'tbody', 'tr', 'th', 'td', 'del', 'span', 'div'
}

ALLOWED_ATTRIBUTES = {
    'a': {'href', 'title', 'target'},
    'code': {'class'},
    'span': {'class'},
}

def sanitize_user_markdown(raw_text):
    """
    Dual-Pass Processing:
    Raw Markdown ---> HTML ---> nh3 Sanitizer (Allowlist Filter) ---> Safe DB Output
    """
    if not raw_text:
        return ""
    
    # 1. Raw Markdown -> HTML
    # We include extra markdown extensions for tables and fenced code blocks
    html = markdown.markdown(raw_text, extensions=['fenced_code', 'tables'])
    
    # 2. HTML -> nh3 Sanitizer with explicit strict allowlist
    cleaned_html = nh3.clean(
        html,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        url_schemes={'http', 'https', 'mailto'}
    )
    
    return cleaned_html


def manager_required(view_func):
    """
    Decorator for views that checks if the user is in the 'Manager' group
    or is a superuser. Returns PermissionDenied (403) if not authorized.
    """
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        if request.user.is_superuser or request.user.groups.filter(name='Manager').exists():
            return view_func(request, *args, **kwargs)
        raise PermissionDenied
    return _wrapped_view


def cashier_or_manager_required(view_func):
    """
    Decorator for views that checks if the user is in the 'Cashier' or 'Manager' group
    or is a superuser. Returns PermissionDenied (403) if not authorized.
    """
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        if (request.user.is_superuser or 
            request.user.groups.filter(name__in=['Cashier', 'Manager']).exists()):
            return view_func(request, *args, **kwargs)
        raise PermissionDenied
    return _wrapped_view
